85% das coisas de Staff
petcomputacaoufrgs/dino-app pull request #119
Opened 2021-02-19 03:13 UTC by prphawk

pf aprovem e nao liguem pro que ta inacabado pq eu preciso mergear esse negocio de uma vezzzzzz

2021-02-21 10:38 UTC, vickyad submitted a review, later dismissed

2021-02-23 00:49 UTC, JPedroSilveira approved these changes

2021-03-03 20:09 UTC, JPedroSilveira requested changes
Bugs relatados no trello

2021-03-22 20:46 UTC, JPedroSilveira requested changes

2021-03-22 20:46 UTC, JPedroSilveira commented on src/App.tsx
> +			updateAuth(isAuthenticated)
Função sendo chamada duas vezes, primeiro em loadAuth()

2021-03-22 20:46 UTC, JPedroSilveira commented on src/App.tsx
> +			const hasUserPermission = await UserService.getPermission()
Faltou adicionar o listenner de UserService em: 
		"AuthService.addUpdateEventListenner(loadData)
		UserSettingsService.addUpdateEventListenner(loadSettings)
		TabControlService.addUpdateEventListenner(loadData)"

2021-03-22 20:46 UTC, JPedroSilveira commented on src/App.tsx
> +			const hasUserPermission = await UserService.getPermission()
Talvez userPermission seria melhor, por ser um enumerados com diferentes tipos de usuário

2021-03-22 20:46 UTC, JPedroSilveira commented on src/App.css
> +	/* white-space: nowrap; */
Remover trecho comentado

2021-03-22 20:46 UTC, JPedroSilveira commented on src/components/dialogs/dino_dialog/props.ts
> +	actions?: React.ReactNode
Tem que ver com o Afonso que tipo seria ideal aqui.
https://stackoverflow.com/questions/58123398/when-to-use-jsx-element-vs-reactnode-vs-reactelement
Tem essa discussão aqui sobre os tipos, acho que ReactNode é muito genérico, mas entre ReactElement e JSXElement eu não sei.

2021-03-22 20:46 UTC, JPedroSilveira commented on src/components/settings/first_settings_dialog/index.tsx
> +			UserSettingsService.save(settings)
Colocando save aqui ele já salva essa configuração na API. Se você removeu o save de cada step na API para evitar que isso ocorra então teria que manter o saveOnlyLocally aqui também e nos outros locais. (Nesse caso só salvaria o resultado final na API).

2021-03-22 20:46 UTC, JPedroSilveira commented on src/constants/api/APIRequestMappingConstants.ts
Abri uma PR para sua revisão nesta branch com uma proposta de renomeação das classes:
 - Uma para paths de HTTP
 - Uma para paths de WebSocket (fica aberta para mudanças que influenciem só o WebSocket)
 - Uma geral com os paths principais

2021-03-22 20:46 UTC, JPedroSilveira commented on src/constants/app_data/DataConstants.ts
> +export default DataConstants
Depois do merge vamos tentar padronizar assim no resto do App, achei lindo

2021-03-22 20:46 UTC, JPedroSilveira commented on src/services/auth/AuthService.ts
> +	private async saveUser(responseBody: AuthResponseDataModel) {
Substitui a função "saveUserAuthData" por essa, fazem a mesma coisa

2021-03-22 20:46 UTC, JPedroSilveira commented on src/types/contact/view/ContactView.ts
> +import EssentialContactEntity from '../database/EssentialContactEntity'
Não usado

2021-03-22 20:46 UTC, JPedroSilveira commented on src/views/main/contacts/contact_dialog_card/content/index.tsx
> +			{ isUniversal ? renderTreatmentListItem('Este contato é universal e aparecerá em todas as agendas de usuários')
Adicionar ao language

2021-03-22 20:46 UTC, JPedroSilveira commented on src/views/main/faq_hub/question_dialog_form/styles.css
>  	padding: 0.5rem 1.5rem !important;
Não referencia nenhum item

2021-03-22 20:46 UTC, JPedroSilveira commented on src/views/main/glossary/styles.css
> +/* .glossary__card_title .icon_button__options {
Remover trecho não utilizado

2021-03-22 20:46 UTC, JPedroSilveira commented on src/views/staff/treatment/treatment_form/index.tsx
> +            /* é importante descontruir o objeto ao atualizá-lo, mesmo com um único atributo, senão ele vira outro. */
Remover comentário

2021-03-22 20:46 UTC, JPedroSilveira commented on src/views/staff/treatment/treatment_list_items/treatment_list_item/index.tsx
> +          {/* TODO: Como fazer pra mudar a aba a partir dum link??? */}
Como assim?

2021-06-25 00:18 UTC, JPedroSilveira approved these changes

2021-06-25 00:20 UTC, merged