FaqItens Universais
petcomputacaoufrgs/dino-app pull request #154
Opened 2021-07-07 00:05 UTC by prphawk

- os faqItems que devem aparecer em todas as faqs são universais e tem treatment.localId nulo/undefined
- a entidade do faqItem do indexedDB tem a propriedade "isUniversal" semelhante à EssentialContact

2021-07-07 16:52 UTC, LeoHernandes approved these changes

2021-07-08 23:50 UTC, prphawk commented on src/views/main/faq_hub/faq_item_form/index.tsx
> +    if(open) setItem(getItem())
pra posterioridade: era esse o erro

2021-07-09 12:40 UTC, vickyad requested changes
![image](https://user-images.githubusercontent.com/44807606/125079002-84f1f680-e099-11eb-8873-cc4fdd471895.png)
* qualquer coisa que eu aperto dá isso

--> outra preocupação que eu tenho, que não é específica dessa PR são esses ícones no tratamento que nem eu sei mais o que significa cada um. Talvez uma legenda? hahahahaha

2021-07-09 19:25 UTC, prphawk commented
> ![image](https://user-images.githubusercontent.com/44807606/125079002-84f1f680-e099-11eb-8873-cc4fdd471895.png)
> 
> * qualquer coisa que eu aperto dá isso
> 
> --> outra preocupação que eu tenho, que não é específica dessa PR são esses ícones no tratamento que nem eu sei mais o que significa cada um. Talvez uma legenda? hahahahaha

oi vic, precisa deletar o banco do indexedDB pq agr tem coisa nova nele dai ele buga assim, dai ele reconstroi o novo

sobre o que significa eu posso botar um pop-iup nos icones dizendo o nome de cada um: FAQ, Perguntas de Usuários & Opções

2021-07-09 22:49 UTC, vickyad approved these changes

2021-07-09 22:49 UTC, merged